<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

// Fase 1 (docs/disseny-migracions-regles-camps.md, "Bloc de llindars de l'Excel"): implementa a la BD els llindars
// numèrics i les repeticions PROPOSATS a l'Excel (docs/nutrievo-camps-rutines-biblioteca.xlsx, columnes taronges
// K–W), redactats per la IA a partir de guies generals (columna "Font"), SENSE validació clínica encara (columnes
// "Estat de validació" i "Valor final validat" queden buides expressament: això és una PROPOSTA, no la confirmació
// d'un nutricionista). Es couen a `docs/pendent-validacio-nutricionista.md`.
//
// No s'hi inclouen els camps on l'Excel no proposa cap valor (objectiu individual, pautat pel metge o pendent
// d'una taula de referències per edat/sexe — Fase 2): fluid_intake (disfàgia/bariàtrica/renal), weight
// (gestacional/embaràs), waist_cm, training_minutes, carb_portion, prepregnancy_bmi, caffeine_cups.
//
// S'apliquen a `mst_library_routine_fields` (per id, exacte com a l'Excel, amb les excepcions per rutina que ja hi
// havia), es propaguen als `mst_routine_fields` existents pel seu `sourceLibraryFieldId` (com la migració
// 2026_09_27_150000) i, amb el cas general (*), als 9 camps de `mst_field_library_items` que en tenen.
return new class extends Migration
{
    private const COLUMNS = [
        'alertMin', 'alertMax', 'alertValue', 'alertLevel', 'alertMinOccurrences', 'alertWindowDays',
        'alertConsecutiveDays', 'trendChangeAbs', 'trendChangePct',
    ];

    // mst_library_routine_fields.id => valors (un id per fila real: mateixes excepcions per rutina que a l'Excel).
    private const LIBRARY_ROUTINE_FIELDS = [
        ['id' => '144defb0-0bc6-469f-aa60-3ad3eb682167', 'alertMin' => null, 'alertMax' => 0, 'alertValue' => null, 'alertLevel' => 'URGENT', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // cough_episodes — Disfàgia: textures i seguretat en menjar
        ['id' => '58c86e54-3f2f-4e3e-88dc-d6c705f25c1c', 'alertMin' => 75, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // intake_pct — Disfàgia: textures i seguretat en menjar
        ['id' => '87010ff5-5362-4fdf-8fa8-99927679ab0c', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => 5], // weight — Disfàgia: textures i seguretat en menjar
        ['id' => 'cb996c70-fb9c-4475-a520-f6823e7a9650', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => 1, 'trendChangePct' => null], // weight — Patró saludable i control de pes
        ['id' => '7dce7904-840b-4e07-bfb0-3eee79907048', 'alertMin' => 2, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // meals — Patró saludable i control de pes
        ['id' => '23dff9be-a569-413e-9a15-c66dcf86a556', 'alertMin' => 3, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // fruit_vegetables — Patró saludable i control de pes
        ['id' => '967ae7d1-ae82-43d0-8a1e-0c2c8cb0ae37', 'alertMin' => 4, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // water — Patró saludable i control de pes
        ['id' => 'b0d4308b-f1d7-4e0a-a00e-fdf26140e7ef', 'alertMin' => 20, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 5, 'trendChangeAbs' => null, 'trendChangePct' => null], // activity_minutes — Patró saludable i control de pes
        ['id' => '78fc1fd2-4fd9-4258-a993-b0c0b80c85ed', 'alertMin' => null, 'alertMax' => 8, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // hunger — Patró saludable i control de pes
        ['id' => 'e75c2a47-7216-4a3e-a39e-012fe809268e', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // sodium_choices — Patró DASH i reducció de sodi
        ['id' => '918289eb-2f2c-4891-bf29-e1706a32cd29', 'alertMin' => 3, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // fruit_veg — Patró DASH i reducció de sodi
        ['id' => '24853a41-7c7f-4166-8530-5b5203da48bf', 'alertMin' => 2, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // whole_grains — Patró DASH i reducció de sodi
        ['id' => 'f085c661-f2f8-4010-a9df-ac85d49b0f08', 'alertMin' => null, 'alertMax' => 2, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // processed_food — Patró DASH i reducció de sodi
        ['id' => 'df6ed056-a444-4482-84b8-5b58c7fe4c2f', 'alertMin' => 4, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // water — Patró DASH i reducció de sodi
        ['id' => 'a6f30e66-3424-4307-9510-d598d31a65d3', 'alertMin' => 75, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // intake_pct — Gent gran: prevenció de la malnutrició
        ['id' => 'faf029ae-0711-42c2-885e-ed3ddd4d9562', 'alertMin' => 3, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // protein_portions — Gent gran: prevenció de la malnutrició
        ['id' => '16c3dd21-59a4-42ab-b1bf-3f3941f6886a', 'alertMin' => 1000, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // fluid_intake — Gent gran: prevenció de la malnutrició
        ['id' => 'fb34295f-9cc7-4b71-b7a8-4f1aa6605ffa', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // appetite — Gent gran: prevenció de la malnutrició
        ['id' => 'ad0c4ab6-7228-4673-ba51-e33d6282d452', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => 5], // weight — Gent gran: prevenció de la malnutrició
        ['id' => '474734d6-7a2e-4aa5-867c-7528263e7ee0', 'alertMin' => 3, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => 2, 'alertWindowDays' => 7, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // gluten_free_meals — Celiaquia: seguiment sense gluten
        ['id' => '9fb2d90e-9644-4fa0-bae6-b806bee8c902', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // cross_contact — Celiaquia: seguiment sense gluten
        ['id' => '5884ec0e-32d6-46f6-82b5-495900bac9f3', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // symptoms — Celiaquia: seguiment sense gluten
        ['id' => 'b3b181c1-8d07-4829-a921-11df2ae62ba9', 'alertMin' => 70, 'alertMax' => 95, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // glucose_fasting — Diabetis gestacional: alimentació i glucosa
        ['id' => 'fe9aca83-3a2b-4212-8b28-c17806999624', 'alertMin' => null, 'alertMax' => 140, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // glucose_1h — Diabetis gestacional: alimentació i glucosa
        ['id' => 'f6919471-e44e-46e0-b357-6511790f4469', 'alertMin' => null, 'alertMax' => 120, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // glucose_after — Diabetis gestacional: alimentació i glucosa
        ['id' => '1d21ce53-b7d7-4496-9bc4-75981322c172', 'alertMin' => null, 'alertMax' => null, 'alertValue' => false, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // medication — Diabetis gestacional: alimentació i glucosa
        ['id' => '27dee35b-0026-4839-b631-c713fc3fa06d', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'URGENT', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // hypo — Diabetis gestacional: alimentació i glucosa
        ['id' => 'db82a9ff-f7f8-4f6a-b7c8-082013055020', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'URGENT', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // ketones — Diabetis gestacional: alimentació i glucosa
        ['id' => '2dc79247-ff38-443d-bdd0-d001157d378c', 'alertMin' => 20, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 5, 'trendChangeAbs' => null, 'trendChangePct' => null], // activity_minutes — Diabetis gestacional: alimentació i glucosa
        ['id' => '98aa76cb-fb0e-4176-9b48-82d94c5748d6', 'alertMin' => 5, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // medas_week_score — Adherència a la dieta mediterrània
        ['id' => 'cfc490e8-a9e4-4624-9a3e-fddd40bc7a4a', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // heartburn — Reflux gastroesofàgic (RGE)
        ['id' => '9ae98774-762d-4567-8242-1a10c5333dc0', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => 3, 'alertWindowDays' => 7, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // regurgitation — Reflux gastroesofàgic (RGE)
        ['id' => '436489ff-aa99-4e26-87a6-f64157d50eb7', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => 4, 'alertWindowDays' => 7, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // late_meal — Reflux gastroesofàgic (RGE)
        ['id' => 'ec79945c-65d7-4e25-8e7e-d236ffa9bef4', 'alertMin' => null, 'alertMax' => null, 'alertValue' => false, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // meds — Reflux gastroesofàgic (RGE)
        ['id' => '3d35daf6-9563-4deb-9c44-687d05d02bb4', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // epigastric_pain — Reflux gastroesofàgic (RGE)
        ['id' => '6df68c6a-2760-44f7-964d-6406987a2168', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // nausea — Reflux gastroesofàgic (RGE)
        ['id' => 'bb817440-0968-427f-8f1c-afd9f02e2e6a', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => 3, 'alertWindowDays' => 7, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // sleep_disturbed — Reflux gastroesofàgic (RGE)
        ['id' => 'a35cb946-3355-457c-a1b1-e2fbdbbd0d6a', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => 3, 'alertWindowDays' => 7, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // rescue_meds — Reflux gastroesofàgic (RGE)
        ['id' => '6afb6b5f-d12a-4f4c-a1d5-24028bca66db', 'alertMin' => null, 'alertMax' => 2, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // heartburn_days — Reflux gastroesofàgic (RGE)
        ['id' => 'd15595c4-511d-4d4b-b42c-933d6c899e16', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => 1, 'trendChangePct' => null], // weight — Reflux gastroesofàgic (RGE)
        ['id' => '15cf1c44-fdc6-4eb1-b59e-d92d13137b80', 'alertMin' => 1, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // bowel_movements — Rutina per restrenyiment
        ['id' => '56024503-57ff-44bc-bc78-542b90b3b7fc', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // straining — Rutina per restrenyiment
        ['id' => 'e30e7a27-dcf4-47a4-b317-6ed387444790', 'alertMin' => 3, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // fiber — Rutina per restrenyiment
        ['id' => '8fe066af-4179-4d39-989f-7ce2322811a9', 'alertMin' => 4, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // water — Rutina per restrenyiment
        ['id' => '363f38bf-14cd-45ed-a19f-2b4b6f532770', 'alertMin' => 20, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 5, 'trendChangeAbs' => null, 'trendChangePct' => null], // activity — Rutina per restrenyiment
        ['id' => '45898388-70af-4612-b4cb-fb9bbf84d8ee', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // pain — Rutina per restrenyiment
        ['id' => '040f1a5e-9dc1-4d34-ae3a-e090fe40c60b', 'alertMin' => 1.5, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // hydration — Nutrició esportiva i rendiment
        ['id' => 'abb5f30f-3db3-4a7d-a422-c1333108024a', 'alertMin' => null, 'alertMax' => 9, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // perceived_effort — Nutrició esportiva i rendiment
        ['id' => '19e3b1d8-a099-47b5-9d39-a5d29f601c78', 'alertMin' => 6, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // sleep_hours — Nutrició esportiva i rendiment
        ['id' => 'df992bed-226b-4dfe-a206-b2155c3207bf', 'alertMin' => null, 'alertMax' => 1, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => 3, 'alertWindowDays' => 7, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // sugary_drinks — Fetge gras (MASLD): pes, alcohol i dieta mediterrània
        ['id' => '85987e0b-9853-473a-b733-c1fecb768a5a', 'alertMin' => null, 'alertMax' => 0, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // alcohol_units — Fetge gras (MASLD): pes, alcohol i dieta mediterrània
        ['id' => 'd74266cd-882a-451c-8c0e-eadaa60017e7', 'alertMin' => 20, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 5, 'trendChangeAbs' => null, 'trendChangePct' => null], // activity_minutes — Fetge gras (MASLD): pes, alcohol i dieta mediterrània
        ['id' => '1cd2a72b-80d2-4231-8cfd-65e9d267ccb5', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => 1, 'trendChangePct' => null], // weight — Fetge gras (MASLD): pes, alcohol i dieta mediterrània
        ['id' => 'dfbb48d3-d383-4dfb-b7be-092d85509333', 'alertMin' => 6, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // medas_score — Fetge gras (MASLD): pes, alcohol i dieta mediterrània
        ['id' => '2ca611e2-f0c4-4fdb-8147-a8704a93fb0a', 'alertMin' => 70, 'alertMax' => 130, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // glucose_before — Diabetis: mètode del plat
        ['id' => '9b73199f-351d-435e-adca-c23f702ad716', 'alertMin' => null, 'alertMax' => 180, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // glucose_after — Diabetis: mètode del plat
        ['id' => 'a6b28c2c-9c35-46fe-bf45-1c9a79084af9', 'alertMin' => null, 'alertMax' => null, 'alertValue' => false, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // medication — Diabetis: mètode del plat
        ['id' => 'f8cbad19-a793-4727-86a2-e6477bb122d3', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'URGENT', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // hypo — Diabetis: mètode del plat
        ['id' => '734a2d47-37a8-4c00-b30d-5d53075613d3', 'alertMin' => 70, 'alertMax' => 130, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // glucose_fasting — Diabetis: mètode del plat
        ['id' => 'bb817da4-20b8-4952-81ef-3270b7b72dbb', 'alertMin' => 100, 'alertMax' => 180, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // glucose_bedtime — Diabetis: mètode del plat
        ['id' => '3bb04737-8de8-4838-b4d5-7354d9977d2d', 'alertMin' => 20, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 5, 'trendChangeAbs' => null, 'trendChangePct' => null], // activity_minutes — Diabetis: mètode del plat
        ['id' => 'e033fe1e-ecdd-40cb-9234-6855597d1e87', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => 1, 'trendChangePct' => null], // weight — Diabetis: mètode del plat
        ['id' => 'd2a49141-d62b-42a3-9001-f3b815a2c300', 'alertMin' => 70, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // time_in_range — Diabetis: mètode del plat
        ['id' => '58367a16-c605-475d-8d49-390c5a8b2770', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // wellbeing_04 — Malaltia inflamatòria intestinal: registre de símptomes
        ['id' => '26e6e4ff-1858-4d28-9590-18c8dd022d74', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // pain_03 — Malaltia inflamatòria intestinal: registre de símptomes
        ['id' => '81c3fb2d-34a8-4091-951c-3118bc1dbba9', 'alertMin' => null, 'alertMax' => 3, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // liquid_stools — Malaltia inflamatòria intestinal: registre de símptomes
        ['id' => 'aa5a860a-07a2-4caf-86a9-b19c8febbc1b', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'URGENT', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // blood_stool — Malaltia inflamatòria intestinal: registre de símptomes
        ['id' => '9d2015b6-fb42-4a39-9288-5d4f4c36fb83', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // interference — Malaltia inflamatòria intestinal: registre de símptomes
        ['id' => '5c263649-920c-4675-9c5b-37b4220f06b2', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'URGENT', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // ibd_complications — Malaltia inflamatòria intestinal: registre de símptomes
        ['id' => '5baff662-ec1c-49a2-87bb-328eca998b74', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => 3], // weight — Malaltia inflamatòria intestinal: registre de símptomes
        ['id' => '9b8c33fd-295f-404b-8c9b-4e90dd602f4e', 'alertMin' => 3, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // fruit_veg — Pediatria: hàbits familiars 5-2-1-0
        ['id' => '07de98ab-7cae-4697-a4db-60774ffb126d', 'alertMin' => null, 'alertMax' => 2, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // screen_time — Pediatria: hàbits familiars 5-2-1-0
        ['id' => '4dd12d6e-f1f5-4b93-85f6-028bf5add2c1', 'alertMin' => 20, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 5, 'trendChangeAbs' => null, 'trendChangePct' => null], // activity_minutes — Pediatria: hàbits familiars 5-2-1-0
        ['id' => 'ffb3a0d8-0295-470c-b74c-9f282c5b7fea', 'alertMin' => null, 'alertMax' => 0, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => 3, 'alertWindowDays' => 7, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // sugary_drinks — Pediatria: hàbits familiars 5-2-1-0
        ['id' => 'b653d6d4-a049-4faa-b03b-73c32f48ae0c', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // nausea_vomiting — Embaràs: pes gestacional i hàbits
        ['id' => '13480461-23be-41a2-ab55-b15bd721aa7a', 'alertMin' => null, 'alertMax' => null, 'alertValue' => false, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // supplements — Embaràs: pes gestacional i hàbits
        ['id' => 'f5d7a22b-1aad-4895-94fa-bc7a2ecf2911', 'alertMin' => 4, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // water — Embaràs: pes gestacional i hàbits
        ['id' => 'f56e3068-d3cd-4ce0-a965-da8b03a77974', 'alertMin' => 60, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // protein_intake — Postoperatori de cirurgia bariàtrica
        ['id' => 'f01880e8-9e22-4143-a61c-25d4d90e6c5d', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // tolerance — Postoperatori de cirurgia bariàtrica
        ['id' => '2f44c5fc-88cf-43a7-a9ae-a08f05d742b2', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // nausea_vomiting — Postoperatori de cirurgia bariàtrica
        ['id' => '86866fd3-2bd6-460d-b351-b07afa85503f', 'alertMin' => null, 'alertMax' => null, 'alertValue' => false, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // supplements — Postoperatori de cirurgia bariàtrica
        ['id' => '3b87a078-fed7-4000-8184-66e48b915043', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => 2, 'alertWindowDays' => 7, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // dumping — Postoperatori de cirurgia bariàtrica
        ['id' => '2888d38a-09d3-43fd-9112-5a0d5c1c50e0', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // dizziness — Postoperatori de cirurgia bariàtrica
        ['id' => 'd980a664-638a-4a76-ad9b-a454c586c79c', 'alertMin' => null, 'alertMax' => 2, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // vomiting_count — Postoperatori de cirurgia bariàtrica
        ['id' => '34931f2e-330a-4f62-b845-c869ce249c13', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => 1, 'trendChangePct' => null], // weight — Postoperatori de cirurgia bariàtrica
        ['id' => '5ced7751-5ec6-4fdc-8916-8fd70ca977c7', 'alertMin' => 1, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // bowel_movements — Postoperatori de cirurgia bariàtrica
        ['id' => 'ab087528-3019-416f-ac41-0f8cf1a04a21', 'alertMin' => null, 'alertMax' => 6, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // protein_portions — Malaltia renal crònica (sense diàlisi)
        ['id' => '7246657c-d520-4ca9-9df2-2a83e6cd1e2c', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // salt_choices — Malaltia renal crònica (sense diàlisi)
        ['id' => '68c54de3-c781-4e9f-8e42-5311d736fbb4', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'URGENT', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // swelling — Malaltia renal crònica (sense diàlisi)
        ['id' => 'e62f376f-8892-47e6-b196-51bf7b2b7187', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => 1, 'trendChangePct' => null], // weight — Malaltia renal crònica (sense diàlisi)
        ['id' => '61e38fb6-c264-4b7b-b68c-e879b2b26b07', 'alertMin' => 3.5, 'alertMax' => 5.0, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // potassium_lab — Malaltia renal crònica (sense diàlisi)
        ['id' => '6ac837cf-89e0-46de-bc38-14dbf4008548', 'alertMin' => 2.5, 'alertMax' => 4.5, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // phosphorus_lab — Malaltia renal crònica (sense diàlisi)
        ['id' => '5dd6521d-096d-4ad3-80c9-7e473b14e2db', 'alertMin' => 75, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // intake_pct — Oncologia: suport nutricional
        ['id' => '82c118e8-6daa-4bfa-b8e1-63c3ca402d03', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // appetite — Oncologia: suport nutricional
        ['id' => 'b352e549-30ea-46ac-8c38-3beedd59588c', 'alertMin' => 3, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // protein_portions — Oncologia: suport nutricional
        ['id' => 'c672e4dc-f2e1-42fc-9e9f-dcef2ab43f6d', 'alertMin' => null, 'alertMax' => null, 'alertValue' => false, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // oral_supplements — Oncologia: suport nutricional
        ['id' => '77f79ec5-379f-4359-a44f-a2e3eda1505f', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // nausea — Oncologia: suport nutricional
        ['id' => '436049d7-dcbb-46ee-acd5-82c454a4bb13', 'alertMin' => null, 'alertMax' => 2, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // vomiting_count — Oncologia: suport nutricional
        ['id' => '2bfa234f-ddc5-4d0a-a5dc-fa62d6b1025f', 'alertMin' => null, 'alertMax' => null, 'alertValue' => true, 'alertLevel' => 'URGENT', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // mouth_sores — Oncologia: suport nutricional
        ['id' => 'c4c920cb-f95b-495a-b82d-cc4b25550c17', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'URGENT', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => 2], // weight — Oncologia: suport nutricional
        ['id' => 'f0f15859-f122-4613-be26-fb623ad112bb', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // bloating — SII: seguiment FODMAP supervisat
        ['id' => '9d9d7bcf-e7a6-4332-8508-f0b0a9f3e395', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // pain — SII: seguiment FODMAP supervisat
        ['id' => '6ce612c4-a749-4ced-a450-b7e795ba9d95', 'alertMin' => 1, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // bowel_movements — SII: seguiment FODMAP supervisat
        ['id' => '3d41a397-4586-4288-bb6c-665c641125b1', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // stress — SII: seguiment FODMAP supervisat
        ['id' => '77fcf139-66d2-4b6b-8436-5eda9b816901', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // interference — SII: seguiment FODMAP supervisat
        ['id' => 'c45b1d4b-5796-46c7-9cdc-3eb89ea1fd0b', 'alertMin' => null, 'alertMax' => 3, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // pain_days — SII: seguiment FODMAP supervisat
        ['id' => 'c9af8f50-90ce-4355-8eac-b70bde119867', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // bowel_satisfaction — SII: seguiment FODMAP supervisat
        ['id' => '4bbbabd2-c973-4917-b8d8-9eb3e934f74e', 'alertMin' => 4, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // fluid_cups — SII: seguiment FODMAP supervisat
        ['id' => '8762f762-ce18-4ea5-a753-637a5f2ab2dd', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // salt_choices — Hipertensió arterial: hàbits per controlar la pressió
        ['id' => '548569c6-b525-4420-a8d6-faf4103eaed2', 'alertMin' => 3, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // fruit_veg — Hipertensió arterial: hàbits per controlar la pressió
        ['id' => '34579d6b-d682-4064-b681-031cddc467a8', 'alertMin' => null, 'alertMax' => 2, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // processed_food — Hipertensió arterial: hàbits per controlar la pressió
        ['id' => '07550127-d5bb-49ab-93c1-e222e897629e', 'alertMin' => null, 'alertMax' => 0, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // alcohol_units — Hipertensió arterial: hàbits per controlar la pressió
        ['id' => 'd0fe062f-4028-4424-a25e-88cd146e834e', 'alertMin' => 20, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 5, 'trendChangeAbs' => null, 'trendChangePct' => null], // activity_minutes — Hipertensió arterial: hàbits per controlar la pressió
        ['id' => 'fad2b73f-e80d-4545-bb9a-d60740c4f369', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => 1, 'trendChangePct' => null], // weight — Hipertensió arterial: hàbits per controlar la pressió
        ['id' => '621bb0f3-1fd2-45ad-a08a-c07e6869f0bd', 'alertMin' => 2, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // healthy_fats — Control de colesterol i salut cardiovascular
        ['id' => 'fdfa999b-df85-4394-9572-86a99e3ef14e', 'alertMin' => 3, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // fiber_portions — Control de colesterol i salut cardiovascular
        ['id' => '1b3e865a-fd7f-4fb6-861c-9b19181b067e', 'alertMin' => null, 'alertMax' => 2, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // saturated_fat_choices — Control de colesterol i salut cardiovascular
        ['id' => '33b3cb08-0bfb-4f79-b336-03e70e0ec870', 'alertMin' => 20, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 5, 'trendChangeAbs' => null, 'trendChangePct' => null], // activity_minutes — Control de colesterol i salut cardiovascular
    ];

    // mst_field_library_items.id => valors (cas general "*", per als camps compartits del picker).
    private const FIELD_LIBRARY_ITEMS = [
        ['id' => '01139e1f-4030-49b5-8af0-00ef526c2886', 'alertMin' => null, 'alertMax' => 8, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // hunger
        ['id' => '16d49fa5-9fb6-4ce2-9eff-a2364bb3c482', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // pain
        ['id' => '99d54ca0-030f-4c9f-b916-3618427852e3', 'alertMin' => 20, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 5, 'trendChangeAbs' => null, 'trendChangePct' => null], // activity_minutes
        ['id' => 'a3f324d2-335c-44b9-ac69-42b74f8e0878', 'alertMin' => 6, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => null, 'trendChangePct' => null], // sleep_hours
        ['id' => 'a5dca3de-4f59-4dbc-ad29-5afa40fc0535', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => null, 'trendChangeAbs' => 1, 'trendChangePct' => null], // weight
        ['id' => 'b7c8fd3d-1f8f-4a14-af04-1f5080bdab37', 'alertMin' => 1, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 3, 'trendChangeAbs' => null, 'trendChangePct' => null], // bowel_movements
        ['id' => 'd467c4f1-91f2-41aa-9892-4857af245222', 'alertMin' => null, 'alertMax' => null, 'alertValue' => false, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // medication
        ['id' => 'dc7998e8-53bd-4f15-9131-015a3fb706b5', 'alertMin' => null, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // bloating
        ['id' => 'ed4bbd06-b1b3-445c-adf5-53349cda8373', 'alertMin' => 4, 'alertMax' => null, 'alertValue' => null, 'alertLevel' => 'REVIEW', 'alertMinOccurrences' => null, 'alertWindowDays' => null, 'alertConsecutiveDays' => 2, 'trendChangeAbs' => null, 'trendChangePct' => null], // water
    ];

    public function up(): void
    {
        foreach (self::LIBRARY_ROUTINE_FIELDS as $row) {
            $id = $row['id'];
            DB::table('mst_library_routine_fields')->where('id', $id)->where('isSensitive', false)->update($this->values($row));

            $updated = DB::table('mst_library_routine_fields')->where('id', $id)->first(self::COLUMNS);
            if ($updated) {
                DB::table('mst_routine_fields')->where('sourceLibraryFieldId', $id)->update($this->values((array) $updated));
            }
        }

        foreach (self::FIELD_LIBRARY_ITEMS as $row) {
            DB::table('mst_field_library_items')->where('id', $row['id'])->where('isSensitive', false)->update($this->values($row));
        }
    }

    public function down(): void
    {
        $ids = array_column(self::LIBRARY_ROUTINE_FIELDS, 'id');
        $reset = array_fill_keys(self::COLUMNS, null) + ['alertLevel' => 'NONE'];

        DB::table('mst_library_routine_fields')->whereIn('id', $ids)->update($reset);
        DB::table('mst_routine_fields')->whereIn('sourceLibraryFieldId', $ids)->update($reset);
        DB::table('mst_field_library_items')->whereIn('id', array_column(self::FIELD_LIBRARY_ITEMS, 'id'))->update($reset);
    }

    private function values(array $row): array
    {
        return array_intersect_key($row, array_flip(self::COLUMNS));
    }
};
